services:
  binance-bot-v1:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: binance_python_bot_v1
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"