services:
  binance-bot:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: binance_php_bot
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app